# Generated by Django 4.2.20 on 2025-09-18 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Controlador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        default="Controlador Padrão",
                        max_length=255,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controladores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nome", "cadastrado_em"],
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_serial",
                    models.CharField(max_length=255, verbose_name="Número Serial"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "tipo_sensor",
                    models.CharField(
                        choices=[("1", "Temperatura"), ("2", "Umidade")],
                        default="1",
                        max_length=30,
                    ),
                ),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "controlador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paginasweb.controlador",
                    ),
                ),
            ],
            options={
                "ordering": ["descricao", "cadastrado_em"],
            },
        ),
        migrations.CreateModel(
            name="Regra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                ("horario_inicio", models.TimeField(verbose_name="Horário de Início")),
                ("horario_fim", models.TimeField(verbose_name="Horário de Fim")),
                ("valor_minimo", models.FloatField(verbose_name="Valor Mínimo")),
                ("valor_maximo", models.FloatField(verbose_name="Valor Máximo")),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paginasweb.sensor",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["descricao", "sensor", "cadastrado_em"],
            },
        ),
        migrations.CreateModel(
            name="Leitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.FloatField()),
                ("data", models.DateTimeField()),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cadastrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leituras",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="paginasweb.sensor",
                    ),
                ),
            ],
            options={
                "ordering": ["sensor", "cadastrado_em"],
            },
        ),
    ]
