# Generated by Django 3.2.25 on 2025-07-31 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginasweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='senha',
        ),
        migrations.AlterField(
            model_name='admin',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cadastro', to=settings.AUTH_USER_MODEL),
        ),
    ]
