# Generated by Django 4.2.20 on 2025-08-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paginasweb", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="controlador",
            options={"ordering": ["nome", "cadastrado_em"]},
        ),
        migrations.AlterModelOptions(
            name="leitura",
            options={"ordering": ["sensor", "cadastrado_em"]},
        ),
        migrations.AlterModelOptions(
            name="regra",
            options={"ordering": ["descricao", "sensor", "cadastrado_em"]},
        ),
        migrations.AlterModelOptions(
            name="sensor",
            options={"ordering": ["descricao", "cadastrado_em"]},
        ),
    ]
