# Generated by Django 4.2.20 on 2025-08-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paginasweb", "0002_alter_controlador_options_alter_leitura_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensor",
            name="tipo_sensor",
            field=models.CharField(
                choices=[(1, "Temperatura"), (2, "Umidade")], default=1, max_length=30
            ),
        ),
    ]
