# Generated by Django 3.2.25 on 2025-08-01 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginasweb', '0002_auto_20250731_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlador',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regra',
            name='usuario',
            field=models.ForeignKey(default=0.7419354838709677, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
