# Generated by Django 4.2.20 on 2025-08-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paginasweb", "0003_sensor_tipo_sensor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="tipo_sensor",
            field=models.CharField(
                choices=[("1", "Temperatura"), ("2", "Umidade")],
                default="1",
                max_length=30,
            ),
        ),
    ]
