# Generated by Django 3.2.25 on 2025-09-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0004_alter_sensor_tipo_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.CharField(choices=[('Temperatura', 'Temperatura'), ('Umidade', 'Umidade')], default='1', max_length=30),
        ),
    ]
