# Generated by Django 3.2.25 on 2025-08-07 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0005_auto_20250731_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leitura',
            name='temperatura',
        ),
        migrations.AddField(
            model_name='leitura',
            name='Controlador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paginasweb.controlador'),
        ),
        migrations.AlterField(
            model_name='leitura',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
