# Generated by Django 3.2.25 on 2025-09-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0006_alter_sensor_tipo_sensor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='tipo_sensor',
        ),
    ]
