# Generated by Django 3.2.25 on 2025-09-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0007_remove_sensor_tipo_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='sensor',
            field=models.CharField(max_length=50),
        ),
    ]
