# Generated by Django 3.2.25 on 2025-06-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0007_alter_cadastro_cadastrado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
            preserve_default=False,
        ),
    ]
