# Generated by Django 3.2.25 on 2025-09-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0008_alter_leitura_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.CharField(choices=[('1', 'Temperatura'), ('2', 'Umidade')], default='1', max_length=30),
        ),
    ]
