# Generated by Django 3.2.25 on 2025-09-06 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0009_sensor_tipo_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paginasweb.sensor'),
        ),
    ]
