# Generated by Django 3.2.25 on 2025-07-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0010_indexcliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regra',
            name='tipo_sensor',
        ),
        migrations.AddField(
            model_name='regra',
            name='controlador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paginasweb.controlador'),
        ),
    ]
