# Generated by Django 3.2.25 on 2025-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0012_admin_usuario_cadastro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='sensor',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
