# Generated by Django 3.2.25 on 2025-07-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0013_auto_20250725_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlador',
            name='cadastro_cliente',
        ),
        migrations.RemoveField(
            model_name='leitura',
            name='tipo_sensor',
        ),
    ]
