# Generated by Django 3.2.25 on 2025-07-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0014_auto_20250725_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regra',
            name='valor_maximo',
            field=models.FloatField(verbose_name='Valor Máximo'),
        ),
        migrations.AlterField(
            model_name='regra',
            name='valor_minimo',
            field=models.FloatField(verbose_name='Valor Mínimo'),
        ),
    ]
