# Generated by Django 3.2.25 on 2025-07-26 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0015_auto_20250726_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlador',
            name='cadastrado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regra',
            name='cadastrado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
