# Generated by Django 3.2.25 on 2025-07-26 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0016_auto_20250726_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regra',
            name='controlador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paginasweb.controlador'),
        ),
    ]
