# Generated by Django 3.2.25 on 2025-07-26 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0017_alter_regra_controlador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regra',
            name='controlador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paginasweb.controlador'),
        ),
    ]
