# Generated by Django 3.2.25 on 2025-07-27 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginasweb', '0019_alter_regra_controlador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControladorAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Controlador Padrão', max_length=255, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SobreAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=255, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
            ],
        ),
        migrations.CreateModel(
            name='RegraAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('horario_inicio', models.CharField(max_length=10, verbose_name='Horário de Início')),
                ('horario_fim', models.CharField(max_length=10, verbose_name='Horário de Fim')),
                ('valor_minimo', models.FloatField(verbose_name='Valor Mínimo')),
                ('valor_maximo', models.FloatField(verbose_name='Valor Máximo')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, max_length=30)),
                ('controlador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paginasweb.controladoradmin')),
            ],
        ),
    ]
